services:
  - type: web
    name: bechedin-api
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx tsc
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
